backfill_history:
  fields:
    months:
      example: 24
      default: 24
      selector:
        number:
          min: 1
          max: 84
          mode: box
    entry_id:
      example: 0123456789abcdef
      selector:
        config_entry:
          integration: estfeed

set_cumulative_reset_at:
  fields:
    reset_at:
      example: "2026-05-18T12:29:58+00:00"
      required: true
      selector:
        datetime:
    entry_id:
      example: 0123456789abcdef
      selector:
        config_entry:
          integration: estfeed
